import type {MissionDefinition,ResidentId} from './neighborhoodStories';
export const PERSONALITIES:Record<ResidentId,{label:string;playful:string;brusque:string;warm:string}>={
  hanh:{label:'Thẳng tính · quý người chịu làm',playful:'Cô cười: “Cháu mà xếp trà nhanh bằng nói đùa thì chợ mình thắng to!”',brusque:'Cô chống tay: “Nói nhanh cũng được, nhưng việc phải làm cẩn thận. Cô không thích hứa suông.”',warm:'“Cháu nói nhẹ nhàng thế cô dễ nhờ. Mình làm từng việc nhé.”'},
  thu:{label:'Khó tính · quan tâm từng chi tiết',playful:'Cô Thu nhịn cười: “Khéo miệng đấy. Nhưng cô vẫn kiểm tra xem cháu xếp đúng chưa!”',brusque:'“Cô lớn tuổi chứ không điếc đâu! Nếu cháu vội thì cứ nói, đừng cáu với cô.”',warm:'“Cô hơi kỹ tính, cháu thông cảm. Cẩn thận một chút thì ai cũng vui.”'},
  nam:{label:'Điềm đạm · thích đùa bằng chữ',playful:'Anh Nam cười: “Một chương truyện hài rồi! Giờ mình viết tiếp chương làm việc nhé.”',brusque:'“Anh hiểu em bận, nhưng đừng gắt với người tới đọc. Mình nói rõ việc cần làm là được.”',warm:'“Cảm ơn em. Chỗ này yên tĩnh, mình làm thong thả nhưng đúng hẹn.”'},
  minh:{label:'Hay kể chuyện · hơi đãng trí',playful:'Bác Minh bật cười: “Hồi bác trẻ cũng tếu như cháu. May bác còn nhớ đường về!”',brusque:'Bác chậm rãi: “Bác kể hơi dài thật. Cháu cứ nói muốn nghe đoạn nào, không cần bực.”',warm:'“Có người chịu ngồi nghe, bác vui lắm. Chuyện khu phố còn nhiều điều hay.”'},
  binh:{label:'Nghiêm nghị · mềm lòng vì cây',playful:'Bác Bình cười khẽ: “Cây chưa biết nghe chuyện cười đâu. Cứ tưới đúng gốc là nó vui!”',brusque:'“Đừng mạnh tay với cây. Cháu có thể không thích bác, nhưng đừng giẫm lên luống hoa.”',warm:'“Cháu làm có tâm thì bác yên tâm. Chậm một chút cũng được.”'},
  lan:{label:'Năng động · thích bày trò',playful:'Lan cười: “Cậu làm trưởng ban pha trò luôn nhé! Nhưng đừng bỏ quên gian hàng đấy.”',brusque:'“Tớ cũng đang vội chứ bộ. Mình chia việc, không cáu với nhau nữa nhé.”',warm:'“Có cậu giúp là tớ yên tâm hơn hẳn. Xong việc mình rủ cả nhóm uống trà!”'},
};
const step=(place:MissionDefinition['steps'][number]['place'],title:string,verb:string,minutes=5,energy=2)=>({place,title,verb,minutes,energy});
export const CITY_EPISODES:MissionDefinition[]=[
  {id:'hanh-labels',resident:'hanh',episode:2,title:'Chợ không bán… mây',branch:'Một chuyện nhầm vui',brief:'Gió thổi đảo bảng giá, cô Hạnh nhờ mang bảng mới từ phố gốm.',steps:[step('oldtown','Nhận bảng giá từ cửa hàng gốm','Nhận bảng giá'),step('market','Đối chiếu tên hàng, sửa bảng “mây” thành “mận”','Sửa bảng giá',8,3)],cash:19000,fans:3,goodwill:3,report:'Cô bật cười: May cháu sửa, không người ta tưởng cô bán cả bầu trời!',after:'Mỗi lần mua mận, cô Hạnh lại nhắc chuyện cái bảng giá.'},
  {id:'hanh-fair',resident:'hanh',episode:2,title:'Sạp nhỏ ra quảng trường',branch:'Việc cần đúng giờ',brief:'Cô Hạnh khó tính với việc xếp sạp; mang đồ hội chợ và giúp cô chuẩn bị.',steps:[step('market','Kiểm đếm ly và trà cho hội chợ','Kiểm đếm đồ',6,3),step('plaza','Bày sạp đúng lối đi, không chắn cửa','Bày sạp',9,4)],cash:23000,fans:3,goodwill:3,report:'Đúng số lượng, đúng chỗ. Cô tưởng cháu chỉ khéo nói, hóa ra còn khéo làm.',after:'Cô Hạnh tin bạn trông sạp trong những lần hội chợ.'},
  {id:'thu-cushions',resident:'thu',episode:2,title:'Đội kiểm tra gối tựa',branch:'Cô Thu kỹ tính',brief:'Cô Thu muốn góc trà ở quảng trường phải gọn và đúng màu.',steps:[step('apartments','Chọn và gói gối tựa cô Thu đã giặt','Gói gối tựa',6,2),step('plaza','Xếp gối cùng màu, chỉnh ghế thẳng hàng','Chỉnh góc ngồi',8,3)],cash:17000,fans:3,goodwill:4,report:'Cô Thu ngắm một vòng: Ghế thẳng rồi, cô duyệt! Cháu chịu được cô kỹ tính đấy.',after:'Cô Thu nhận bạn vào “đội chỉnh ghế” của khu phố.'},
  {id:'thu-radio',resident:'thu',episode:2,title:'Chiếc đài cứ hát quảng cáo',branch:'Một buổi chiều vui',brief:'Chiếc đài của cô Thu bị lạc kênh; tìm bác Minh nhờ chỉ lại tần số.',steps:[step('lake','Hỏi bác Minh kênh nhạc cô Thu thích','Hỏi tần số',4,1),step('apartments','Dò đúng kênh nhạc, thử nút âm lượng','Dò đài',7,2)],cash:14000,fans:4,goodwill:4,report:'Cuối cùng cũng hết quảng cáo nồi cơm! Cô cười, rồi mời cháu nghe một bài.',after:'Mỗi chiều khu tập thể có tiếng nhạc nhẹ từ chiếc đài cũ.'},
  {id:'nam-riddle',resident:'nam',episode:2,title:'Truy tìm câu đố trà sữa',branch:'Trò chơi tìm chữ',brief:'Anh Nam tổ chức trò tìm chữ. Ghép gợi ý ở phố cổ, sân đình và hiệu sách.',steps:[step('oldtown','Tìm chữ TRÀ trên thiệp hàng gốm','Đọc gợi ý',4,1),step('temple','Nhận chữ SỮA trên thẻ hội làng','Nhận thẻ chữ',4,1),step('library','Ghép câu đố và treo thẻ trò chơi','Ghép câu đố',7,2)],cash:20000,fans:5,goodwill:3,report:'Đáp án là trà sữa, mà cả xóm chạy đi tìm! Anh Nam dành một góc cho tiệm của em.',after:'Trò tìm chữ trở thành hoạt động vui của câu lạc bộ đọc sách.'},
  {id:'nam-silence',resident:'nam',episode:2,title:'Thư viện có nhạc… quá to',branch:'Nói chuyện để hòa giải',brief:'Nhóm hội chợ thử loa quá lớn. Mang lời nhắn lịch sự rồi tạo góc đọc yên tĩnh.',steps:[step('plaza','Nhờ nhóm nhạc chỉnh loa quay xa hiệu sách','Trao đổi với nhóm nhạc',6,2),step('library','Xếp biển “đọc nhỏ thôi” và ghế đọc','Sắp góc yên tĩnh',8,3)],cash:22000,fans:3,goodwill:5,report:'Bên kia vẫn có nhạc, bên này vẫn đọc được. Hóa ra nói chuyện khéo là đủ.',after:'Anh Nam và nhóm nhạc thống nhất giờ tập, không còn cáu nhau.'},
  {id:'minh-photo',resident:'minh',episode:2,title:'Bác đứng nhầm phía camera',branch:'Chụp ảnh kỷ niệm',brief:'Bác Minh muốn ảnh ba góc phố. Giúp bác chọn chỗ đứng và lấy ảnh ở phố gốm.',steps:[step('riverside','Giúp bác tạo dáng nhìn về phía ống kính','Chọn góc ảnh',6,2),step('temple','Ghi lại mái đình bác yêu thích','Chụp mái đình',5,2),step('oldtown','Nhận ảnh kỷ niệm đã in','Nhận ảnh',4,1)],cash:18000,fans:4,goodwill:5,report:'Lần này bác không chụp mỗi sau gáy nữa! Cảm ơn cháu đã kiên nhẫn.',after:'Bác Minh giữ tấm ảnh thành phố trong quyển sổ cũ.'},
  {id:'minh-tour',resident:'minh',episode:2,title:'Hướng dẫn viên quên bản đồ',branch:'Một vòng thành phố',brief:'Bác nhớ chuyện xưa nhưng quên tuyến đi. Đánh dấu lộ trình cho buổi dạo của người cao tuổi.',steps:[step('oldtown','Đánh dấu điểm nghỉ ở phố cổ','Ghi điểm nghỉ',5,2),step('plaza','Đặt sơ đồ đi bộ cạnh ghế chờ','Đặt sơ đồ',5,2),step('lake','Đọc lại tuyến cho bác Minh','Nhắc tuyến đi',5,1)],cash:21000,fans:4,goodwill:4,report:'Bác kể chuyện, cháu nhớ đường. Đúng một đội rồi!',after:'Buổi đi bộ của các bác có thêm bản đồ và điểm nghỉ rõ ràng.'},
  {id:'binh-kite',resident:'binh',episode:2,title:'Cây không phải móc treo diều',branch:'Một trò nghịch nhỏ',brief:'Chiếc diều vướng cành thấp. Thu dây ở đường ven sông và mang trả Lan, không làm gãy cành.',steps:[step('riverside','Gỡ dây diều khỏi cành thấp bằng sào','Gỡ dây diều',8,4),step('school','Trả diều và nhắc nhóm bạn giữ cây','Trả chiếc diều',4,2)],cash:15000,fans:5,goodwill:4,report:'Diều về với chủ, cành cây còn nguyên. Bác Bình cố nghiêm mặt nhưng vẫn cười.',after:'Lan rủ bạn thả diều ở chỗ trống, xa hàng cây.'},
  {id:'binh-bricks',resident:'binh',episode:2,title:'Viên gạch nghiêng làm bác cáu',branch:'Chăm phố cẩn thận',brief:'Bác Bình phát hiện gạch sân đình bị xô lệch. Nhận gạch dự phòng và chỉnh lối đi.',steps:[step('oldtown','Nhận gạch dự phòng từ cô bán gốm','Nhận gạch',4,2),step('temple','Chỉnh hàng gạch sân, gom vữa và quét sạch','Chỉnh lối gạch',12,6)],cash:24000,fans:3,goodwill:5,report:'Được rồi, giờ đi không vấp nữa. Bác khó tính vì muốn mọi người an toàn thôi.',after:'Lối vào sân đình được chăm, bác Bình bớt cau mày mỗi lần đi qua.'},
  {id:'lan-quiz',resident:'lan',episode:2,title:'Hội thi mặt nghiêm túc',branch:'Bày trò cho hội chợ',brief:'Lan nghĩ ra hội thi kể chuyện cười không được cười. Chuẩn bị thẻ trò chơi và sân khấu.',steps:[step('library','Nhờ anh Nam chọn chuyện cười phù hợp','Chọn thẻ chuyện',7,2),step('plaza','Bày thẻ và thử trò cùng đội hội chợ','Thử hội thi',8,3)],cash:18000,fans:6,goodwill:3,report:'Lan thua ngay vòng đầu vì tự cười! Cậu chuẩn bị trò này vui thật đấy.',after:'Góc trò chơi ở quảng trường lúc nào cũng có người cười.'},
  {id:'lan-colors',resident:'lan',episode:2,title:'Cờ hội chợ bị đảo màu',branch:'Giải quyết cùng bạn',brief:'Các bạn tranh nhau cách xếp cờ. Nhận dây cờ ở phố cổ rồi xếp theo mẫu Lan thống nhất.',steps:[step('oldtown','Nhận dây cờ đủ ba màu','Nhận dây cờ',4,2),step('plaza','Phân màu và gắn cờ theo mẫu','Xếp dây cờ',9,4)],cash:22000,fans:4,goodwill:4,report:'Đỏ, vàng, xanh đúng mẫu rồi! Lan cảm ơn cậu vì đã chia việc thay vì cùng cáu.',after:'Nhóm hội chợ học được cách bàn bạc và chia việc.'},
  ...(['hanh','thu','nam','minh','binh','lan'] as const).map((resident,i)=>({id:`${resident}-tea-finale`,resident,episode:3,title:['Cô Hạnh mở tiệc trà','Buổi trà cô Thu duyệt','Đọc sách cùng hương trà','Kể chuyện bên ấm trà','Trà và một mảng xanh','Tiệc trà của hội chợ'][i],branch:'Cuộc hẹn của thành phố',brief:'Cùng hàng xóm chuẩn bị cuộc hẹn uống trà ở quảng trường Đông Phong.',steps:[step('shop','Chuẩn bị bảng menu và bàn đón khách của tiệm','Chuẩn bị tiệm',8,3),step('plaza','Sắp góc trà, lời mời và ghế cho hàng xóm','Sắp cuộc hẹn',10,4)],cash:30000,fans:8,goodwill:6,report:'Cả nhóm đã có một chỗ ngồi cùng nhau. Tiệm Phố Nhỏ trở thành điểm hẹn của thành phố.',after:'Mọi người hẹn quay lại tiệm sau hội chợ.'})),
];
