import type { Customer } from "./types";

// Fictional neighborhood regulars; existing IDs remain stable for older saves.
export const NEIGHBORS: Customer[] = [
  {
    id: "hanh",
    name: "Cô Hạnh",
    hair: "#35342e",
    shirt: "#906c89",
    skin: "#ba855e",
    archetype: "Bán hàng ngoài chợ",
    patience: "chill",
    favorite: "peach-tea",
    greeting: "Cô ngồi bàn nghỉ chân chút. Cho cô ít đường thôi nhé.",
    good: ["Mát quá, mai cô ghé nữa.", "Pha vừa miệng cô đó."],
    okay: ["Cũng được, hơi ngọt chút con à."],
    bad: ["Con xem lại giúp cô, hình như nhầm món rồi."],
  },
  {
    id: "tu",
    name: "Chú Tư",
    hair: "#797369",
    shirt: "#68736a",
    skin: "#a77b59",
    archetype: "Thợ sửa xe đầu hẻm",
    patience: "chill",
    favorite: "classic-milk-tea",
    greeting: "Chú mới xong ca, cho chú một ly mang về.",
    good: ["Ngon đó, bữa sau chú dẫn bạn ghé."],
    okay: ["Ừ, uống cũng ổn."],
    bad: ["Ly này chưa đúng ý chú lắm."],
  },
  {
    id: "minh",
    name: "Minh",
    hair: "#272a25",
    shirt: "#488259",
    skin: "#b5845c",
    archetype: "Tài xế giao hàng",
    patience: "impatient",
    favorite: "peach-tea",
    greeting: "Mình lấy mang đi, đang chờ chuyến tiếp theo.",
    good: ["Đúng món, cảm ơn quán!"],
    okay: ["Hơi khác mọi lần nhưng uống được."],
    bad: ["Bạn xem lại đơn giúp mình với."],
  },
  {
    id: "lan",
    name: "Lan",
    hair: "#292722",
    shirt: "#ebdfcb",
    skin: "#c99873",
    archetype: "Nhân viên văn phòng",
    patience: "normal",
    favorite: "matcha-latte",
    greeting: "Mình ngồi làm việc một lát nhé.",
    good: ["Vừa vị, quán cũng dễ ngồi."],
    okay: ["Lần sau bớt đá chút chắc ngon hơn."],
    bad: ["Mình gọi món khác mà bạn."],
  },
  {
    id: "phuc",
    name: "Phúc",
    hair: "#2e2b26",
    shirt: "#a66d42",
    skin: "#d5a57b",
    archetype: "Sinh viên kiến trúc",
    patience: "normal",
    favorite: "classic-milk-tea",
    greeting: "Em đợi bạn ở bàn. Cho em ly size lớn nhé.",
    good: ["Ngon anh chị ơi!"],
    okay: ["Em thấy cũng được."],
    bad: ["Hình như hơi sai công thức ạ."],
  },
  {
    id: "mai",
    name: "Bà Mai",
    hair: "#a9a397",
    shirt: "#5f7f86",
    skin: "#bf9676",
    archetype: "Khách trong xóm",
    patience: "chill",
    favorite: "peach-tea",
    greeting: "Bà muốn thử trà đào, không cần ngọt nhiều đâu.",
    good: ["Mát dễ uống, cảm ơn cháu."],
    okay: ["Hơi ngọt với bà, lần sau chỉnh nhé."],
    bad: ["Cháu đọc lại món giúp bà nhé."],
  },
  {
    id: "thao",
    name: "Thảo",
    hair: "#242d28",
    shirt: "#9db4b9",
    skin: "#d3a27a",
    archetype: "Điều dưỡng tan ca",
    patience: "normal",
    favorite: "matcha-latte",
    greeting: "Mới tan ca, cho mình ly mang đi nha.",
    good: ["Vừa đúng thứ mình cần lúc này."],
    okay: ["Ổn rồi, cảm ơn bạn."],
    bad: ["Mình muốn đổi về đúng món đã gọi."],
  },
  {
    id: "hai",
    name: "Anh Hải",
    hair: "#332f29",
    shirt: "#477187",
    skin: "#a8774f",
    archetype: "Thợ điện công trình",
    patience: "impatient",
    favorite: "classic-milk-tea",
    greeting: "Anh nghỉ trưa chút, pha anh ly nhiều đá nhé.",
    good: ["Mát thật, uống đã quá."],
    okay: ["Tạm được em à."],
    bad: ["Ly này sai món rồi em ơi."],
  },
];
